version: '3'

services:
  database:
    container_name: wanted_db
    image: mysql:8.0.34
    volumes:
      - ./docker/mysql:/var/lib/mysql:rw
    ports:
      - "3307:3306"
    restart: always
    command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
    environment:
#      MYSQL_ROOT_HOST: %
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wanted
      MYSQL_USER: wanted
      MYSQL_PASSWORD: wanted123
    networks:
      - wanted_network

  application:
    container_name: wanted_app
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - database
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://database:3306/wanted?serverTimezone=Asia/Seoul&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: wanted
      SPRING_DATASOURCE_PASSWORD: wanted123
    networks:
      - wanted_network

networks:
  wanted_network:
